### ISSUE TITLE
Trouble downloading long (155 min) private youtube stream 

### ISSUE THREAD

**Issue by digitalfabric92** [leerob/youtube-to-mp3#1]
The app hangs at 100% for 30mins+ when attempting to download mp3 from a long private stream video. 

It might not technically be an issue, but it is something that needs to be improved.

**Comment by leerob** [comment]
Yeah, I kind of figured it wouldn't work with that long of videos. I can add it to the list of future improvements.

Contributions are always welcome too 😄
