### ISSUE TITLE
Electron problem

### ISSUE THREAD

**Issue by ib157** [leerob/youtube-to-mp3#10]
i got this error
![image](https://user-images.githubusercontent.com/33505525/36949570-38216afa-1fe2-11e8-86e7-c3c57f6e3fda.png)

**Comment by leerob** [comment]
Does it fail with any video or just that specific one?

**Comment by Mercylas** [comment]
![image](https://user-images.githubusercontent.com/8311059/39670011-490d6758-50c8-11e8-8ff1-3bab3a07c755.png)
Can confirm its not an edge case

**Comment by diegofrayo** [comment]
I have the same problem

**Comment by ENT8R** [comment]
Updating [`ytdl-core`](https://www.npmjs.com/package/ytdl-core) to the latest version `0.20.4` solves the issue for me...

**Comment by HarounAns** [comment]
The issue is happening again:

![image](https://user-images.githubusercontent.com/20847319/64723737-1775de80-d49f-11e9-91ef-15b754844fdd.png)

I am up to date with the latest module for ytdl-core @ 0.28.2

**Comment by HarounAns** [comment]
Doesn't seem like the same error. Does anyone have it working currently?
I'm using Windows btw and yarn

**Comment by HarounAns** [comment]
It seems like youtube make a change recently that broke everything
https://github.com/fent/node-ytdl-core/issues/486

**Comment by HarounAns** [comment]
Working with version 0.29.7 of ytdl-core!
