### ISSUE TITLE
Doesn't Work on Ubuntu

### ISSUE THREAD

**Issue by lapak10** [leerob/youtube-to-mp3#2]
the app did start but even after getting to 100% completed. No popup to save the file option came up. I tried 2 min long video from youtube.com so file size cannot be the issue.

**Comment by jerry5chang** [comment]
I got the following message when I execute "npm start", any suggestion? macOS 10.13.1

Electron could not be found. No hard resets for you!
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by leerob** [comment]
There was probably an issue with the server used to retrieve the converted YouTube videos. Could you try restarting the application and attempting to download again?

I'm thinking it would be helpful if it showed an error message in this case.

**Comment by lapak10** [comment]
**Ubuntu Error:** 
![ScreenShot](https://tryimg.com/u/2017/11/21/Screenshot-from-2017-11-21-22-11-38.png "Error Ubuntu")

**Comment by leerob** [comment]
I'm sorry you're having issues ☹️  I haven't tested on ubuntu, only for macOS. I'm definitely open to contributions for adding ubuntu support though!

**Comment by lapak10** [comment]
I am not able to test it in Mac, is it working as expected there??
..Also I'll try to submit a patch for Ubuntu (Linux builds) system.

**Comment by IT-MikeS** [comment]
I believe that if PR #5 goes through the direction change should fix this issue, as the save dialog is handled through electron/nodejs fs, not system reaction which will make the download handle more consistant

**Comment by leerob** [comment]
Closing this because it should resolved with the latest mater merge.
