### ISSUE TITLE
Got error message on macOS 10.13.1

### ISSUE THREAD

**Issue by jerry5chang** [leerob/youtube-to-mp3#3]
I got the following message when I execute "npm start" on macOS 10.13.1
, any suggestion?

Electron could not be found. No hard resets for you!
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by leerob** [comment]
Is electron properly installed?

```bash
npm install electron --save-dev
```

Maybe try something here? 
https://github.com/yan-foto/electron-reload/issues/16

**Comment by IT-MikeS** [comment]
I had issues with electron reload on windows as well, after doing an update on dependencies ( updated to newest electron instead of prebuilt and new electron reload) all went fine.

**Comment by leerob** [comment]
Would you mind submitting a PR?

**Comment by leerob** [comment]
Disregard - I see you did! Thanks!

**Comment by IT-MikeS** [comment]
Yeah I did for a few things, feel free to message me if need be about any change I made

**Comment by leerob** [comment]
@jerry5chang Could you try pulling down this PR https://github.com/leerob/youtube-to-mp3/pull/4 and seeing if it fixes the issues you were having?

**Comment by IT-MikeS** [comment]
@jerry5chang @leerob this warning is harmless. Some people over at this issue thread ([https://github.com/spyder-ide/spyder/issues/3730#issue-191337353](url)) have had some luck suppressing it, but some haven't. Rest assured nothing will malfunction in the app because of the warnings 😄.

**Comment by leerob** [comment]
Going to close this based on @IT-MikeS's comment. Hope it's working for you @jerry5chang!
