### ISSUE TITLE
Blank screen and I'm getting an error

### ISSUE THREAD

**Issue by kieranz** [leerob/youtube-to-mp3#9]
The error is: Not allowed to load local resource: file:///D:/youtube-to-mp3/app/index.html data:text/html,chro…:1

No idea why.

![image](https://user-images.githubusercontent.com/25729836/34450191-9e329924-ecc8-11e7-9883-5356def28db6.png)

**Comment by IT-MikeS** [comment]
From what I see its pointing at a `D` drive for the file, strange I'll pull down the master and see if I can reproduce it.

**Comment by leerob** [comment]
I'm having trouble reproducing this one - going to close. Sorry about that @kieranz! Let me know if you have any other issues.
